# config.yaml

# Paths
dataset:
  train_csv: "../dataset/tw_food_101/tw_food_101_train.csv"
  test_csv: "../dataset/tw_food_101/tw_food_101_test_list.csv"
  train_dir: "../dataset/tw_food_101/train"
  test_dir: "../dataset/tw_food_101/test"

# Model & Training
model:
  name: "resnet18"
  num_classes: 101
  pretrained: true

training:
  batch_size: 32
  epochs: 15
  learning_rate: 0.0001
  num_workers: 2
  device: "cuda"

# Output
output:
  save_dir: "../outputs"
  save_name: "tw_food101_best.pth"

#loging
logging:
  tensorboard_log_dir: "../runs/test"
# Augmentation
transforms:
  resize: [224, 224]
  random_horizontal_flip: true
  random_rotation: 10
